version: '4.29'
services:
  calculator_microservice:
    container_name: calculator_microservice_container
    image: calculator_microservice_image
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/calculator_microservice_volume
    networks:
      - calculator_microservice_network
    environment:
      - PORT=8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/check-health || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 30s
    restart: on-failure